export const evolution = [
    {
      id: 1,
      title: "2000s: Queues in banking halls",
      image: "https://images.unsplash.com/photo-1634937734976-7b0432527d5d?q=80&w=1993&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      description: `The 2000s represented the height of traditional banking in Ghana, and like many parts of the world, it was defined by long, winding queues in brick-and-mortar banking halls. Customers often had to dedicate an entire morning or afternoon to complete a simple transaction. The environment was typically crowded, with numbered tickets, endless waiting, and bank tellers buried in mountains of paperwork. Passbooks, cheque books, and physical cash ruled the day. It was not uncommon for a customer to be told to return the next day because “the system was down.” Transactions were handled manually, leaving room for human error and security lapses. There was a strong human element to it—relationships with personal bankers mattered—but the experience was far from efficient. People lived around the bank’s operating hours, and for the working class, accessing your own money meant sacrificing precious time. This was an era where banking was rigid, reactive, and dependent on location, yet deeply familiar to everyone who lived through it.`
    },
    {
      id: 2,
      title: "2010s: Mobile banking introduction",
      image: "https://images.unsplash.com/photo-1610737241336-371badac3b66?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      description: `The 2010s brought a wave of transformation that shifted the foundation of banking into the palms of customers. Mobile banking started as a novelty—something only the tech-savvy explored—but quickly grew into a necessity. With the rise of mobile phones, especially in Africa, banks began introducing USSD services and basic mobile apps. Customers could suddenly perform actions like checking account balances, transferring funds, and purchasing airtime without stepping foot in a banking hall. This dramatically increased banking accessibility for both urban professionals and remote communities. It was the beginning of self-service banking—transactions were now in your control, anytime, anywhere. Mobile banking reduced reliance on human tellers, shortened turnaround times, and expanded financial services to a wider population. However, the digital shift also came with growing pains: concerns about security, low smartphone penetration, and the learning curve for less tech-literate users. Despite this, the decade was pivotal—it broke down walls and opened the gates to what banking could truly become: agile, inclusive, and 24/7.`
    },
    {
      id: 3,
      title: "Now: First Atlantic’s digital banking experience",
      image: "https://images.unsplash.com/photo-1526628953301-3e589a6a8b74?q=80&w=2006&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      description: `Today, First Atlantic Bank has reimagined banking to meet the expectations of a hyper-connected, on-the-go generation. The digital experience is no longer just functional—it’s beautifully crafted, intuitive, and secure. Customers enjoy full-spectrum banking through our mobile app and online platforms, allowing them to manage their finances effortlessly with just a few taps. Whether it’s making instant transfers, scheduling payments, opening accounts, or even applying for loans, everything is available in a seamless user experience. Biometric logins, real-time notifications, and encrypted transactions ensure peace of mind. But what truly sets the experience apart is its personalization—users are no longer anonymous account holders, but valued individuals whose financial journeys are supported and enhanced. With smart notifications, budgeting insights, and lifestyle-based tools, our digital banking is not just reactive but proactive. At First Atlantic, banking is no longer confined to buildings—it’s an extension of your life, accessible 24/7, designed to empower and evolve with you.`
    },
    {
      id: 4,
      title: "Future: What our future looks like",
      image: "https://images.unsplash.com/photo-1583154683839-2d49400c3d65?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      description: `Looking ahead, First Atlantic Bank envisions a future where banking becomes less visible but more powerful—woven into the very fabric of your daily life. Imagine a world where you can initiate transactions by speaking naturally to your device, where AI-powered financial assistants proactively advise you on how to grow your savings or optimize your spending. This is a future where banking doesn’t interrupt your life—it enhances it. We're exploring technologies like voice-activated banking, facial recognition authentication, blockchain-backed smart contracts, and AI-driven customer support that’s instant, intelligent, and emotionally aware. You'll no longer need to remember to save—your bank will do it for you, based on your behavior and goals. Investing, budgeting, borrowing, and transacting will feel as effortless as having a conversation. We’re building a future where financial empowerment is democratized, where banking becomes anticipatory instead of reactive, and where every interaction feels personalized, secure, and deeply human—even when powered by machines.`
    }
  ]
  